### ISSUE TITLE
crash on server start up 1.9.4

### ISSUE THREAD

**Issue by SDUBZ** [TheCricket/Chisel3#4] opened 2016-06-20 04:10 UTC
added chisel 3 to my server today and got this crash
http://pastebin.com/PDgVc45M

**Comment by Cirrus0** [comment] 2016-06-20 13:26
Happening to me as well, seems like the mod is not aware, that it is running on a server

**Comment by TheCricket** [comment] 2016-06-20 20:34
Duplicate of #1 which i've already fixed in dev :)

**Comment by TheCricket** [comment] 2016-06-20 20:34
Been working out some github issues so haven't been able to push :)

**Closed by TheCricket** 2016-06-20 20:34 UTC
Labels: duplicate
